### ISSUE TITLE
在高并发情况下，有数据错误的问题

### ISSUE THREAD

**Issue by guoxiaogang1991** [eselltech/RtbJavaLib#1]
在并发情况下，调用这个方法的时候，
 RtbManager rtbManager = RtbManager.getInstance();
        rtbManager.init(appId, appKey, unicode);
rtbManager.dynamicReport(trackUrl, new IRTBRequest.Callback() {

}
没有加锁，而unicode 一直在不变化，异步回调的时候 unicode 可以不一致，线程不安全。

**Comment by eselltech** [comment]
已修复 请使用0.0.6以上版本
